version = 1

test_patterns = [  
  "**/test/**"
]

exclude_patterns = [
  "**/examples/**"
]

[[analyzers]]  
name = "cxx"
enabled = true
[analyzers.meta]
  misra_compliance = true
  cyclomatic_complexity_threshold = "medium"
